name: XCode Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app
    
    - name: Xcode build iOS App
      run: |
        cd Supermercado/
        xcodebuild clean build -project Supermercado.xcodeproj -scheme Supermercado -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.4'
